// <auto-generated />
using System;
using BrasilBurger.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrasilBurger.Web.Migrations
{
    [DbContext(typeof(BrasilBurgerContext))]
    partial class BrasilBurgerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrasilBurger.Web.Models.Burger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Etat")
                        .HasColumnType("boolean")
                        .HasColumnName("etat");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.ToTable("burger", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Etat")
                        .HasColumnType("text")
                        .HasColumnName("etat");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    b.Property<string>("Mode")
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric")
                        .HasColumnName("montant");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("commande", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.CommandeBurger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBurger")
                        .HasColumnType("integer")
                        .HasColumnName("id_burger");

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("id_commande");

                    b.Property<int>("Qte")
                        .HasColumnType("integer")
                        .HasColumnName("qte");

                    b.HasKey("Id");

                    b.HasIndex("IdBurger");

                    b.HasIndex("IdCommande");

                    b.ToTable("commande_burger", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.CommandeComplement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("id_commande");

                    b.Property<int>("IdComplement")
                        .HasColumnType("integer")
                        .HasColumnName("id_complement");

                    b.Property<int>("Qte")
                        .HasColumnType("integer")
                        .HasColumnName("qte");

                    b.HasKey("Id");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdComplement");

                    b.ToTable("commande_complement", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.CommandeMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("id_commande");

                    b.Property<int>("IdMenu")
                        .HasColumnType("integer")
                        .HasColumnName("id_menu");

                    b.Property<int>("Qte")
                        .HasColumnType("integer")
                        .HasColumnName("qte");

                    b.HasKey("Id");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdMenu");

                    b.ToTable("commande_menu", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Complement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Etat")
                        .HasColumnType("boolean")
                        .HasColumnName("etat");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.ToTable("complement", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cle");

                    b.Property<string>("Valeur")
                        .HasColumnType("text")
                        .HasColumnName("valeur");

                    b.HasKey("Id");

                    b.HasIndex("Cle")
                        .IsUnique();

                    b.ToTable("configuration", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Livraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("id_commande");

                    b.Property<int>("IdLivreur")
                        .HasColumnType("integer")
                        .HasColumnName("id_livreur");

                    b.HasKey("Id");

                    b.HasIndex("IdCommande")
                        .IsUnique();

                    b.HasIndex("IdLivreur");

                    b.ToTable("livraison", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Livreur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("livreur", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.MenuBurger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBurger")
                        .HasColumnType("integer")
                        .HasColumnName("id_burger");

                    b.Property<int>("IdMenu")
                        .HasColumnType("integer")
                        .HasColumnName("id_menu");

                    b.HasKey("Id");

                    b.HasIndex("IdBurger");

                    b.HasIndex("IdMenu");

                    b.ToTable("menu_burger", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("id_commande");

                    b.Property<string>("Mode")
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric")
                        .HasColumnName("montant");

                    b.HasKey("Id");

                    b.HasIndex("IdCommande")
                        .IsUnique();

                    b.ToTable("paiement", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Quartier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdZone")
                        .HasColumnType("integer")
                        .HasColumnName("id_zone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.HasIndex("IdZone");

                    b.ToTable("quartier", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<decimal>("PrixLivraison")
                        .HasColumnType("numeric")
                        .HasColumnName("prix_livraison");

                    b.HasKey("Id");

                    b.ToTable("zone", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Commande", b =>
                {
                    b.HasOne("BrasilBurger.Web.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.CommandeBurger", b =>
                {
                    b.HasOne("BrasilBurger.Web.Models.Burger", "Burger")
                        .WithMany("CommandeBurgers")
                        .HasForeignKey("IdBurger")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurger.Web.Models.Commande", "Commande")
                        .WithMany("CommandeBurgers")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Burger");

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.CommandeComplement", b =>
                {
                    b.HasOne("BrasilBurger.Web.Models.Commande", "Commande")
                        .WithMany("CommandeComplements")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurger.Web.Models.Complement", "Complement")
                        .WithMany("CommandeComplements")
                        .HasForeignKey("IdComplement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Complement");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.CommandeMenu", b =>
                {
                    b.HasOne("BrasilBurger.Web.Models.Commande", "Commande")
                        .WithMany("CommandeMenus")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurger.Web.Models.Menu", "Menu")
                        .WithMany("CommandeMenus")
                        .HasForeignKey("IdMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Livraison", b =>
                {
                    b.HasOne("BrasilBurger.Web.Models.Commande", "Commande")
                        .WithOne("Livraison")
                        .HasForeignKey("BrasilBurger.Web.Models.Livraison", "IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurger.Web.Models.Livreur", "Livreur")
                        .WithMany("Livraisons")
                        .HasForeignKey("IdLivreur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Livreur");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.MenuBurger", b =>
                {
                    b.HasOne("BrasilBurger.Web.Models.Burger", "Burger")
                        .WithMany("MenuBurgers")
                        .HasForeignKey("IdBurger")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurger.Web.Models.Menu", "Menu")
                        .WithMany("MenuBurgers")
                        .HasForeignKey("IdMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Burger");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Paiement", b =>
                {
                    b.HasOne("BrasilBurger.Web.Models.Commande", "Commande")
                        .WithOne("Paiement")
                        .HasForeignKey("BrasilBurger.Web.Models.Paiement", "IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Quartier", b =>
                {
                    b.HasOne("BrasilBurger.Web.Models.Zone", "Zone")
                        .WithMany("Quartiers")
                        .HasForeignKey("IdZone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Burger", b =>
                {
                    b.Navigation("CommandeBurgers");

                    b.Navigation("MenuBurgers");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Commande", b =>
                {
                    b.Navigation("CommandeBurgers");

                    b.Navigation("CommandeComplements");

                    b.Navigation("CommandeMenus");

                    b.Navigation("Livraison");

                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Complement", b =>
                {
                    b.Navigation("CommandeComplements");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Livreur", b =>
                {
                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Menu", b =>
                {
                    b.Navigation("CommandeMenus");

                    b.Navigation("MenuBurgers");
                });

            modelBuilder.Entity("BrasilBurger.Web.Models.Zone", b =>
                {
                    b.Navigation("Quartiers");
                });
#pragma warning restore 612, 618
        }
    }
}
